// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pjiawbvzsabknljxpsux.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBqaWF3YnZ6c2Fia25sanhwc3V4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzY3ODIxNjYsImV4cCI6MjA5MjM1ODE2Nn0.ZRoTI1fFhZ7IS2yKaJwL4D-ZjGY_KEpjBjwYio1YQ2Y";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});